'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoError as InnoErrorElement, defineCustomElement as defineInnoError } from "@innomotics/brand-experience/dist/components/inno-error.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoErrorEvents = NonNullable<unknown>;

const InnoError: StencilReactComponent<InnoErrorElement, InnoErrorEvents> = /*@__PURE__*/ createComponent<InnoErrorElement, InnoErrorEvents>({
    tagName: 'inno-error',
    elementClass: InnoErrorElement,
    react: React,
    events: {} as InnoErrorEvents,
    defineCustomElement: defineInnoError
});

export default InnoError;
