'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type InnoModalHeaderCustomEvent } from "@innomotics/brand-experience";
import { InnoModalHeader as InnoModalHeaderElement, defineCustomElement as defineInnoModalHeader } from "@innomotics/brand-experience/dist/components/inno-modal-header.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoModalHeaderEvents = { onCloseClick: EventName<InnoModalHeaderCustomEvent<Event>> };

const InnoModalHeader: StencilReactComponent<InnoModalHeaderElement, InnoModalHeaderEvents> = /*@__PURE__*/ createComponent<InnoModalHeaderElement, InnoModalHeaderEvents>({
    tagName: 'inno-modal-header',
    elementClass: InnoModalHeaderElement,
    react: React,
    events: { onCloseClick: 'closeClick' } as InnoModalHeaderEvents,
    defineCustomElement: defineInnoModalHeader
});

export default InnoModalHeader;
