'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoTimePicker as InnoTimePickerElement, defineCustomElement as defineInnoTimePicker } from "@innomotics/brand-experience/dist/components/inno-time-picker.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoTimePickerEvents = { onValueChange: EventName<CustomEvent<any>> };

const InnoTimePicker: StencilReactComponent<InnoTimePickerElement, InnoTimePickerEvents> = /*@__PURE__*/ createComponent<InnoTimePickerElement, InnoTimePickerEvents>({
    tagName: 'inno-time-picker',
    elementClass: InnoTimePickerElement,
    react: React,
    events: { onValueChange: 'valueChange' } as InnoTimePickerEvents,
    defineCustomElement: defineInnoTimePicker
});

export default InnoTimePicker;
