'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoStatusMessage as InnoStatusMessageElement, defineCustomElement as defineInnoStatusMessage } from "@innomotics/brand-experience/dist/components/inno-status-message.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoStatusMessageEvents = { onCloseMessage: EventName<CustomEvent<any>> };

const InnoStatusMessage: StencilReactComponent<InnoStatusMessageElement, InnoStatusMessageEvents> = /*@__PURE__*/ createComponent<InnoStatusMessageElement, InnoStatusMessageEvents>({
    tagName: 'inno-status-message',
    elementClass: InnoStatusMessageElement,
    react: React,
    events: { onCloseMessage: 'closeMessage' } as InnoStatusMessageEvents,
    defineCustomElement: defineInnoStatusMessage
});

export default InnoStatusMessage;
