'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoModalContent as InnoModalContentElement, defineCustomElement as defineInnoModalContent } from "@innomotics/brand-experience/dist/components/inno-modal-content.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoModalContentEvents = NonNullable<unknown>;

const InnoModalContent: StencilReactComponent<InnoModalContentElement, InnoModalContentEvents> = /*@__PURE__*/ createComponent<InnoModalContentElement, InnoModalContentEvents>({
    tagName: 'inno-modal-content',
    elementClass: InnoModalContentElement,
    react: React,
    events: {} as InnoModalContentEvents,
    defineCustomElement: defineInnoModalContent
});

export default InnoModalContent;
