'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ExpandedChangedEvent, type InnoPaneCustomEvent } from "@innomotics/brand-experience";
import { InnoPane as InnoPaneElement, defineCustomElement as defineInnoPane } from "@innomotics/brand-experience/dist/components/inno-pane.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoPaneEvents = { onExpandedChanged: EventName<InnoPaneCustomEvent<ExpandedChangedEvent>> };

const InnoPane: StencilReactComponent<InnoPaneElement, InnoPaneEvents> = /*@__PURE__*/ createComponent<InnoPaneElement, InnoPaneEvents>({
    tagName: 'inno-pane',
    elementClass: InnoPaneElement,
    react: React,
    events: { onExpandedChanged: 'expandedChanged' } as InnoPaneEvents,
    defineCustomElement: defineInnoPane
});

export default InnoPane;
