'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type DateChange, type InnoDatePickerDropdownCustomEvent } from "@innomotics/brand-experience";
import { InnoDatePickerDropdown as InnoDatePickerDropdownElement, defineCustomElement as defineInnoDatePickerDropdown } from "@innomotics/brand-experience/dist/components/inno-date-picker-dropdown.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoDatePickerDropdownEvents = { onDateChange: EventName<InnoDatePickerDropdownCustomEvent<DateChange>> };

const InnoDatePickerDropdown: StencilReactComponent<InnoDatePickerDropdownElement, InnoDatePickerDropdownEvents> = /*@__PURE__*/ createComponent<InnoDatePickerDropdownElement, InnoDatePickerDropdownEvents>({
    tagName: 'inno-date-picker-dropdown',
    elementClass: InnoDatePickerDropdownElement,
    react: React,
    events: { onDateChange: 'dateChange' } as InnoDatePickerDropdownEvents,
    defineCustomElement: defineInnoDatePickerDropdown
});

export default InnoDatePickerDropdown;
