'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoRadio as InnoRadioElement, defineCustomElement as defineInnoRadio } from "@innomotics/brand-experience/dist/components/inno-radio.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoRadioEvents = { onValueChange: EventName<CustomEvent<string>> };

const InnoRadio: StencilReactComponent<InnoRadioElement, InnoRadioEvents> = /*@__PURE__*/ createComponent<InnoRadioElement, InnoRadioEvents>({
    tagName: 'inno-radio',
    elementClass: InnoRadioElement,
    react: React,
    events: { onValueChange: 'valueChange' } as InnoRadioEvents,
    defineCustomElement: defineInnoRadio
});

export default InnoRadio;
