'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoButton as InnoButtonElement, defineCustomElement as defineInnoButton } from "@innomotics/brand-experience/dist/components/inno-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoButtonEvents = NonNullable<unknown>;

const InnoButton: StencilReactComponent<InnoButtonElement, InnoButtonEvents> = /*@__PURE__*/ createComponent<InnoButtonElement, InnoButtonEvents>({
    tagName: 'inno-button',
    elementClass: InnoButtonElement,
    react: React,
    events: {} as InnoButtonEvents,
    defineCustomElement: defineInnoButton
});

export default InnoButton;
