'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type InnoDragAndDropCustomEvent } from "@innomotics/brand-experience";
import { InnoDragAndDrop as InnoDragAndDropElement, defineCustomElement as defineInnoDragAndDrop } from "@innomotics/brand-experience/dist/components/inno-drag-and-drop.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoDragAndDropEvents = { onFilesChanged: EventName<InnoDragAndDropCustomEvent<Array<File>>> };

const InnoDragAndDrop: StencilReactComponent<InnoDragAndDropElement, InnoDragAndDropEvents> = /*@__PURE__*/ createComponent<InnoDragAndDropElement, InnoDragAndDropEvents>({
    tagName: 'inno-drag-and-drop',
    elementClass: InnoDragAndDropElement,
    react: React,
    events: { onFilesChanged: 'filesChanged' } as InnoDragAndDropEvents,
    defineCustomElement: defineInnoDragAndDrop
});

export default InnoDragAndDrop;
