'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type InnoAccordionCustomEvent } from "@innomotics/brand-experience";
import { InnoAccordion as InnoAccordionElement, defineCustomElement as defineInnoAccordion } from "@innomotics/brand-experience/dist/components/inno-accordion.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoAccordionEvents = { onCollapsedChanged: EventName<InnoAccordionCustomEvent<{ element: HTMLInnoAccordionElement, collapsed: boolean }>> };

const InnoAccordion: StencilReactComponent<InnoAccordionElement, InnoAccordionEvents> = /*@__PURE__*/ createComponent<InnoAccordionElement, InnoAccordionEvents>({
    tagName: 'inno-accordion',
    elementClass: InnoAccordionElement,
    react: React,
    events: { onCollapsedChanged: 'collapsedChanged' } as InnoAccordionEvents,
    defineCustomElement: defineInnoAccordion
});

export default InnoAccordion;
