'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type DateChange, type InnoDatePickerCustomEvent } from "@innomotics/brand-experience";
import { InnoDatePicker as InnoDatePickerElement, defineCustomElement as defineInnoDatePicker } from "@innomotics/brand-experience/dist/components/inno-date-picker.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoDatePickerEvents = { onDateChange: EventName<InnoDatePickerCustomEvent<DateChange>> };

const InnoDatePicker: StencilReactComponent<InnoDatePickerElement, InnoDatePickerEvents> = /*@__PURE__*/ createComponent<InnoDatePickerElement, InnoDatePickerEvents>({
    tagName: 'inno-date-picker',
    elementClass: InnoDatePickerElement,
    react: React,
    events: { onDateChange: 'dateChange' } as InnoDatePickerEvents,
    defineCustomElement: defineInnoDatePicker
});

export default InnoDatePicker;
