'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoSelect as InnoSelectElement, defineCustomElement as defineInnoSelect } from "@innomotics/brand-experience/dist/components/inno-select.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoSelectEvents = {
    onValueChanged: EventName<CustomEvent<string>>,
    onItemIsFavorited: EventName<CustomEvent<any>>,
    onItemIsUnfavorited: EventName<CustomEvent<any>>,
    onFavoriteItemsChanged: EventName<CustomEvent<any>>,
    onDropdownClosed: EventName<CustomEvent<void>>
};

const InnoSelect: StencilReactComponent<InnoSelectElement, InnoSelectEvents> = /*@__PURE__*/ createComponent<InnoSelectElement, InnoSelectEvents>({
    tagName: 'inno-select',
    elementClass: InnoSelectElement,
    react: React,
    events: {
        onValueChanged: 'valueChanged',
        onItemIsFavorited: 'itemIsFavorited',
        onItemIsUnfavorited: 'itemIsUnfavorited',
        onFavoriteItemsChanged: 'favoriteItemsChanged',
        onDropdownClosed: 'dropdownClosed'
    } as InnoSelectEvents,
    defineCustomElement: defineInnoSelect
});

export default InnoSelect;
