'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoProgressBar as InnoProgressBarElement, defineCustomElement as defineInnoProgressBar } from "@innomotics/brand-experience/dist/components/inno-progress-bar.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoProgressBarEvents = NonNullable<unknown>;

const InnoProgressBar: StencilReactComponent<InnoProgressBarElement, InnoProgressBarEvents> = /*@__PURE__*/ createComponent<InnoProgressBarElement, InnoProgressBarEvents>({
    tagName: 'inno-progress-bar',
    elementClass: InnoProgressBarElement,
    react: React,
    events: {} as InnoProgressBarEvents,
    defineCustomElement: defineInnoProgressBar
});

export default InnoProgressBar;
