'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoFooterItem as InnoFooterItemElement, defineCustomElement as defineInnoFooterItem } from "@innomotics/brand-experience/dist/components/inno-footer-item.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoFooterItemEvents = NonNullable<unknown>;

const InnoFooterItem: StencilReactComponent<InnoFooterItemElement, InnoFooterItemEvents> = /*@__PURE__*/ createComponent<InnoFooterItemElement, InnoFooterItemEvents>({
    tagName: 'inno-footer-item',
    elementClass: InnoFooterItemElement,
    react: React,
    events: {} as InnoFooterItemEvents,
    defineCustomElement: defineInnoFooterItem
});

export default InnoFooterItem;
