'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoLoader as InnoLoaderElement, defineCustomElement as defineInnoLoader } from "@innomotics/brand-experience/dist/components/inno-loader.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoLoaderEvents = NonNullable<unknown>;

const InnoLoader: StencilReactComponent<InnoLoaderElement, InnoLoaderEvents> = /*@__PURE__*/ createComponent<InnoLoaderElement, InnoLoaderEvents>({
    tagName: 'inno-loader',
    elementClass: InnoLoaderElement,
    react: React,
    events: {} as InnoLoaderEvents,
    defineCustomElement: defineInnoLoader
});

export default InnoLoader;
