'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoIcon as InnoIconElement, defineCustomElement as defineInnoIcon } from "@innomotics/brand-experience/dist/components/inno-icon.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoIconEvents = NonNullable<unknown>;

const InnoIcon: StencilReactComponent<InnoIconElement, InnoIconEvents> = /*@__PURE__*/ createComponent<InnoIconElement, InnoIconEvents>({
    tagName: 'inno-icon',
    elementClass: InnoIconElement,
    react: React,
    events: {} as InnoIconEvents,
    defineCustomElement: defineInnoIcon
});

export default InnoIcon;
