'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type InnoTabItemCustomEvent, type TabClickDetail } from "@innomotics/brand-experience";
import { InnoTabItem as InnoTabItemElement, defineCustomElement as defineInnoTabItem } from "@innomotics/brand-experience/dist/components/inno-tab-item.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoTabItemEvents = { onTabClick: EventName<InnoTabItemCustomEvent<TabClickDetail>> };

const InnoTabItem: StencilReactComponent<InnoTabItemElement, InnoTabItemEvents> = /*@__PURE__*/ createComponent<InnoTabItemElement, InnoTabItemEvents>({
    tagName: 'inno-tab-item',
    elementClass: InnoTabItemElement,
    react: React,
    events: { onTabClick: 'tabClick' } as InnoTabItemEvents,
    defineCustomElement: defineInnoTabItem
});

export default InnoTabItem;
