'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoModal as InnoModalElement, defineCustomElement as defineInnoModal } from "@innomotics/brand-experience/dist/components/inno-modal.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoModalEvents = {
    onDialogClose: EventName<CustomEvent<any>>,
    onDialogDismiss: EventName<CustomEvent<any>>
};

const InnoModal: StencilReactComponent<InnoModalElement, InnoModalEvents> = /*@__PURE__*/ createComponent<InnoModalElement, InnoModalEvents>({
    tagName: 'inno-modal',
    elementClass: InnoModalElement,
    react: React,
    events: {
        onDialogClose: 'dialogClose',
        onDialogDismiss: 'dialogDismiss'
    } as InnoModalEvents,
    defineCustomElement: defineInnoModal
});

export default InnoModal;
