'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoModalFooter as InnoModalFooterElement, defineCustomElement as defineInnoModalFooter } from "@innomotics/brand-experience/dist/components/inno-modal-footer.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoModalFooterEvents = NonNullable<unknown>;

const InnoModalFooter: StencilReactComponent<InnoModalFooterElement, InnoModalFooterEvents> = /*@__PURE__*/ createComponent<InnoModalFooterElement, InnoModalFooterEvents>({
    tagName: 'inno-modal-footer',
    elementClass: InnoModalFooterElement,
    react: React,
    events: {} as InnoModalFooterEvents,
    defineCustomElement: defineInnoModalFooter
});

export default InnoModalFooter;
