'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoInput as InnoInputElement, defineCustomElement as defineInnoInput } from "@innomotics/brand-experience/dist/components/inno-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoInputEvents = { onValueChanged: EventName<CustomEvent<string | number>> };

const InnoInput: StencilReactComponent<InnoInputElement, InnoInputEvents> = /*@__PURE__*/ createComponent<InnoInputElement, InnoInputEvents>({
    tagName: 'inno-input',
    elementClass: InnoInputElement,
    react: React,
    events: { onValueChanged: 'valueChanged' } as InnoInputEvents,
    defineCustomElement: defineInnoInput
});

export default InnoInput;
