'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoTab as InnoTabElement, defineCustomElement as defineInnoTab } from "@innomotics/brand-experience/dist/components/inno-tab.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoTabEvents = { onSelectedChange: EventName<CustomEvent<number>> };

const InnoTab: StencilReactComponent<InnoTabElement, InnoTabEvents> = /*@__PURE__*/ createComponent<InnoTabElement, InnoTabEvents>({
    tagName: 'inno-tab',
    elementClass: InnoTabElement,
    react: React,
    events: { onSelectedChange: 'selectedChange' } as InnoTabEvents,
    defineCustomElement: defineInnoTab
});

export default InnoTab;
