'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoBreadcrumb as InnoBreadcrumbElement, defineCustomElement as defineInnoBreadcrumb } from "@innomotics/brand-experience/dist/components/inno-breadcrumb.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoBreadcrumbEvents = { onItemClick: EventName<CustomEvent<{ itemIndex: number, label: string }>> };

const InnoBreadcrumb: StencilReactComponent<InnoBreadcrumbElement, InnoBreadcrumbEvents> = /*@__PURE__*/ createComponent<InnoBreadcrumbElement, InnoBreadcrumbEvents>({
    tagName: 'inno-breadcrumb',
    elementClass: InnoBreadcrumbElement,
    react: React,
    events: { onItemClick: 'itemClick' } as InnoBreadcrumbEvents,
    defineCustomElement: defineInnoBreadcrumb
});

export default InnoBreadcrumb;
