'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoFooter as InnoFooterElement, defineCustomElement as defineInnoFooter } from "@innomotics/brand-experience/dist/components/inno-footer.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoFooterEvents = NonNullable<unknown>;

const InnoFooter: StencilReactComponent<InnoFooterElement, InnoFooterEvents> = /*@__PURE__*/ createComponent<InnoFooterElement, InnoFooterEvents>({
    tagName: 'inno-footer',
    elementClass: InnoFooterElement,
    react: React,
    events: {} as InnoFooterEvents,
    defineCustomElement: defineInnoFooter
});

export default InnoFooter;
