'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoPaginator as InnoPaginatorElement, defineCustomElement as defineInnoPaginator } from "@innomotics/brand-experience/dist/components/inno-paginator.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoPaginatorEvents = {
    onPageSelected: EventName<CustomEvent<number>>,
    onItemCountChanged: EventName<CustomEvent<number>>
};

const InnoPaginator: StencilReactComponent<InnoPaginatorElement, InnoPaginatorEvents> = /*@__PURE__*/ createComponent<InnoPaginatorElement, InnoPaginatorEvents>({
    tagName: 'inno-paginator',
    elementClass: InnoPaginatorElement,
    react: React,
    events: {
        onPageSelected: 'pageSelected',
        onItemCountChanged: 'itemCountChanged'
    } as InnoPaginatorEvents,
    defineCustomElement: defineInnoPaginator
});

export default InnoPaginator;
