'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoTableBase as InnoTableBaseElement, defineCustomElement as defineInnoTableBase } from "@innomotics/brand-experience/dist/components/inno-table-base.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoTableBaseEvents = NonNullable<unknown>;

const InnoTableBase: StencilReactComponent<InnoTableBaseElement, InnoTableBaseEvents> = /*@__PURE__*/ createComponent<InnoTableBaseElement, InnoTableBaseEvents>({
    tagName: 'inno-table-base',
    elementClass: InnoTableBaseElement,
    react: React,
    events: {} as InnoTableBaseEvents,
    defineCustomElement: defineInnoTableBase
});

export default InnoTableBase;
