'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { InnoBreadcrumbItem as InnoBreadcrumbItemElement, defineCustomElement as defineInnoBreadcrumbItem } from "@innomotics/brand-experience/dist/components/inno-breadcrumb-item.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type InnoBreadcrumbItemEvents = NonNullable<unknown>;

const InnoBreadcrumbItem: StencilReactComponent<InnoBreadcrumbItemElement, InnoBreadcrumbItemEvents> = /*@__PURE__*/ createComponent<InnoBreadcrumbItemElement, InnoBreadcrumbItemEvents>({
    tagName: 'inno-breadcrumb-item',
    elementClass: InnoBreadcrumbItemElement,
    react: React,
    events: {} as InnoBreadcrumbItemEvents,
    defineCustomElement: defineInnoBreadcrumbItem
});

export default InnoBreadcrumbItem;
