
import * as d from './components';

export const DIRECTIVES = [
  d.InnoAccordion,
  d.InnoBreadcrumb,
  d.InnoBreadcrumbItem,
  d.InnoButton,
  d.InnoCheckbox,
  d.InnoDatePicker,
  d.InnoDatePickerDropdown,
  d.InnoDragAndDrop,
  d.InnoError,
  d.InnoFooter,
  d.InnoFooterItem,
  d.InnoIcon,
  d.InnoInput,
  d.InnoLoader,
  d.InnoModal,
  d.InnoModalContent,
  d.InnoModalFooter,
  d.InnoModalHeader,
  d.InnoPaginator,
  d.InnoPane,
  d.InnoPopover,
  d.InnoProgressBar,
  d.InnoRadio,
  d.InnoSelect,
  d.InnoSelectItem,
  d.InnoSplit,
  d.InnoSplitGutter,
  d.InnoSplitItem,
  d.InnoStatusMessage,
  d.InnoTab,
  d.InnoTabItem,
  d.InnoTableBase,
  d.InnoTimePicker,
  d.InnoToggle
];
