name: build

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.sha = ${{ github.sha }}"
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/install

  build:
    runs-on: ubuntu-latest
    needs: [install]
    container:
      image: node:18.12.1
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/build-cache
      - uses: ./.github/workflows/actions/build
      - name: Upload docs
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: packages/webdocs/build

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: [build]
    container:
      image: node:18.12.1
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/build-cache
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-build
          if-no-files-found: error
          path: |
            packages/stencil-lib/dist
            packages/react-lib/dist
            packages/vue-lib/dist
            packages/angular-lib/dist
            packages/fonts/dist
            packages/icon-lib/dist